#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Motor,  port1,           release,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		if(SensorValue[dgtl1]){
			motor[release] = 50;
			} else if(SensorValue[dgtl2]){
			motor[release] = -50;
			} else {
			motor[release] = 0;
		}
	}
}
